### ISSUE TITLE
why are you deleting the downloads folder?

### ISSUE THREAD

**Issue by prateekmedia** [notusknot/dotfiles#2]
https://github.com/notusknot/dotfiles/blob/ad10e570dba9cdd9be6357d8aab7df4d4b0d2bc8/.config/bspwm/bspwmrc#L11

**Comment by notusknot** [comment]
I keep my downloads in a seperate folder and Brave automatically creates the Downloads folder, which I don't want in the home directory

**Comment by prateekmedia** [comment]
@notusknot Ok but like me if someone tries your dots then first thing that will happen is their downloads folder would be removed.

**Comment by notusknot** [comment]
You're right. I [fixed the issue.](https://github.com/notusknot/dotfiles/commit/ed221871cc75bc935ad5fee4edb7abfa1b64613c) Apologies for any inconveniences this might've caused.
